name: docker-app
channels:
  - conda-forge
  - defaults
dependencies:
  - airflow=2.3.0
  - apache-airflow=2.3.0
  - apache-airflow-providers-postgres=4.1.0
  - black=21.12b0
  - python=3.9
  